spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/ordersdb}
    username: ${DB_USER:orders_user}
    password: ${DB_PASS:orders_pass}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true